services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  website:
    build:
      context: ./website
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - app-network
    command: sh -c "sleep 3 && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  chat:
    build:
      context: ./chat
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - app-network
    command: sh -c "sleep 3 && uvicorn app.main:app --host 0.0.0.0 --port 8001"

  nginx:
    image: nginx:1.27.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - website
      - chat

volumes:
  db-data:

networks:
  app-network:
