"""Add owner_id to chat_rooms

Revision ID: 05a49a403b60
Revises: dd6b4cd4a84c
Create Date: 2024-10-28 01:15:32.115623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a49a403b60'
down_revision: Union[str, None] = 'dd6b4cd4a84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
