"""Add edited and deleted columns to messages

Revision ID: 41ca15353f75
Revises: 05a49a403b60
Create Date: 2024-10-28 20:20:37.533680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ca15353f75'
down_revision: Union[str, None] = '05a49a403b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('edited', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('last_edited_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'last_edited_timestamp')
    op.drop_column('messages', 'deleted')
    op.drop_column('messages', 'edited')
    # ### end Alembic commands ###
